table

CREATE TABLE TAPRES
   (NUMERO INT)

INSERT INTO TPARES (NUMERO) VALUES (15)
UPDATE TPARES SET NUMERO = 400 WHERE NUMERO=4
DELETE FROM PARES



View

 CREATE  VIEW DATOS_EMPLEADO AS 
  SELECT NOMBRE_1,APELLIDO_1,TELEFONO,EMAIL
 FROM EMPLEADOS 
 WHERE IDENTIFICACION = 12;

Function


CREATE FUNCTION [dbo].[FECHA_SERVIDOR]()
RETURNS INT 
AS
BEGIN
DECLARE @AÑO INT
SET @AÑO = (SELECT YEAR(GETDATE()))
RETURN @AÑO
END
GO



procedure

CREATE PROCEDURE  llenarTablaPares
 as
DECLARE @NUMBER INT = 0
WHILE @NUMBER <=  100
	BEGIN
	IF (@NUMBER % 2)= 0 
		insert into pares(numero)values(@NUMBER)	
		SET @NUMBER+= 1 
	END  
GO