/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.vista;

import com.carlos.controlador.*;
import com.formdev.flatlaf.intellijthemes.*;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author carli
 */
public class LoginUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Login_Usuarios
     */
    public LoginUsuarios() {
        initComponents();
         Conectar_Jboton.setIcon(setIcono("/com/carlos/imagenes/conectar.png", Conectar_Jboton));
         Limpiar_Jboton.setIcon(setIcono("/com/carlos/imagenes/limpiar.png", Limpiar_Jboton));
        setIconImage(new ImageIcon(getClass().getResource("/com/carlos/imagenes/sql.png")).getImage());
    }

    public void autocompletar() {
        switch (Motores_Jbox.getSelectedIndex()) {
            case 0 -> {
                Usuario_Jtext.setText("carlos160003602");
                Contraseña_Jtext.setText("carlos375");
                Instancia_Jtext.setText("xe");
                Puerto_Jtext.setText("1521");
                IP_Jtext.setText("localhost");
            }
            case 1 -> {
                Usuario_Jtext.setText("carlos160003602");
                Contraseña_Jtext.setText("carlos375");
                Base_datos_Jtext.setText("talleres");
                Puerto_Jtext.setText("1433");
                IP_Jtext.setText("asus_carlos_a");
            }
        }
    }

    public void deteccion_motor() {
        switch (Motores_Jbox.getSelectedIndex()) {
            case 0 -> {
                Base_datos_Jtext.setText("");
                Base_datos_Jtext.setEnabled(false);
                Base_datos_Jlabel.setEnabled(false);
                Instancia_Jtext.setEnabled(true);
                Instancia_Jlabel.setEnabled(true);
            }
            case 1 -> {
                Instancia_Jtext.setText("");
                Instancia_Jtext.setEnabled(false);
                Instancia_Jlabel.setEnabled(false);
                Base_datos_Jtext.setEnabled(true);
                Base_datos_Jlabel.setEnabled(true);
            }
        }
    }

    public boolean campos() {
        if (Motores_Jbox.getSelectedIndex() == -1 || Usuario_Jtext.getText().length() == 0 || Contraseña_Jtext.getText().length() == 0
                || Puerto_Jtext.getText().length() == 0 || IP_Jtext.getText().length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "COMPLETE LOS CAMPOS NESESARIOS", "ADVERTENCIA", 2);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel Panel_BD = new javax.swing.JPanel();
        Motor_Jlabel = new javax.swing.JLabel();
        Usuario_Jlabel = new javax.swing.JLabel();
        Contraseña_Jlabel = new javax.swing.JLabel();
        Motores_Jbox = new javax.swing.JComboBox<>();
        Usuario_Jtext = new javax.swing.JTextField();
        Contraseña_Jtext = new javax.swing.JPasswordField();
        Panel_Instancia = new javax.swing.JPanel();
        IP_Jlabel = new javax.swing.JLabel();
        Puerto_Jlabel = new javax.swing.JLabel();
        IP_Jtext = new javax.swing.JTextField();
        Puerto_Jtext = new javax.swing.JTextField();
        Instancia_Jlabel = new javax.swing.JLabel();
        Instancia_Jtext = new javax.swing.JTextField();
        Limpiar_Jboton = new javax.swing.JButton();
        Base_datos_Jlabel = new javax.swing.JLabel();
        Base_datos_Jtext = new javax.swing.JTextField();
        Conectar_Jboton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Usuarios");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        Panel_BD.setBackground(new java.awt.Color(255, 255, 255));
        Panel_BD.setInheritsPopupMenu(true);
        Panel_BD.setName("Panel_BD"); // NOI18N

        Motor_Jlabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Motor_Jlabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Motor_Jlabel.setText("Motor de Bases de datos");

        Usuario_Jlabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Usuario_Jlabel.setText("Usuario");

        Contraseña_Jlabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Contraseña_Jlabel.setText("Contraseña");

        Motores_Jbox.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Motores_Jbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Oracle", "SQL Server", "MySQL", "PostgreSQL", "Fire Bird" }));
        Motores_Jbox.setSelectedIndex(-1);
        Motores_Jbox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Motores_JboxItemStateChanged(evt);
            }
        });
        Motores_Jbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Motores_JboxActionPerformed(evt);
            }
        });

        Usuario_Jtext.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        Contraseña_Jtext.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        Contraseña_Jtext.setToolTipText("");

        Panel_Instancia.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Instancia.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        IP_Jlabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        IP_Jlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IP_Jlabel.setText("IP servidor");

        Puerto_Jlabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Puerto_Jlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Puerto_Jlabel.setText("Puerto");

        IP_Jtext.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        Puerto_Jtext.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Puerto_Jtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Puerto_JtextActionPerformed(evt);
            }
        });

        Instancia_Jlabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Instancia_Jlabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Instancia_Jlabel.setText("Instancia");

        Instancia_Jtext.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Instancia_Jtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instancia_JtextActionPerformed(evt);
            }
        });

        Limpiar_Jboton.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Limpiar_Jboton.setText("Limpiar");
        Limpiar_Jboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Limpiar_JbotonActionPerformed(evt);
            }
        });

        Base_datos_Jlabel.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N
        Base_datos_Jlabel.setText("Base de datos");

        Base_datos_Jtext.setFont(new java.awt.Font("Microsoft Tai Le", 0, 14)); // NOI18N

        Conectar_Jboton.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        Conectar_Jboton.setText("Conectar");
        Conectar_Jboton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Conectar_JbotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_InstanciaLayout = new javax.swing.GroupLayout(Panel_Instancia);
        Panel_Instancia.setLayout(Panel_InstanciaLayout);
        Panel_InstanciaLayout.setHorizontalGroup(
            Panel_InstanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InstanciaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(Panel_InstanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Panel_InstanciaLayout.createSequentialGroup()
                        .addComponent(Base_datos_Jlabel)
                        .addGap(18, 18, 18)
                        .addComponent(Base_datos_Jtext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_InstanciaLayout.createSequentialGroup()
                        .addComponent(Puerto_Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Puerto_Jtext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_InstanciaLayout.createSequentialGroup()
                        .addComponent(IP_Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IP_Jtext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_InstanciaLayout.createSequentialGroup()
                        .addComponent(Instancia_Jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Instancia_Jtext, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 56, Short.MAX_VALUE))
            .addGroup(Panel_InstanciaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Conectar_Jboton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Limpiar_Jboton)
                .addGap(36, 36, 36))
        );
        Panel_InstanciaLayout.setVerticalGroup(
            Panel_InstanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InstanciaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_InstanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_InstanciaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Instancia_Jlabel))
                    .addComponent(Instancia_Jtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Panel_InstanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_InstanciaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(IP_Jlabel))
                    .addComponent(IP_Jtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Panel_InstanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puerto_Jtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Puerto_Jlabel))
                .addGap(20, 20, 20)
                .addGroup(Panel_InstanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_InstanciaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Base_datos_Jlabel))
                    .addComponent(Base_datos_Jtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_InstanciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Limpiar_Jboton)
                    .addComponent(Conectar_Jboton))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Panel_BDLayout = new javax.swing.GroupLayout(Panel_BD);
        Panel_BD.setLayout(Panel_BDLayout);
        Panel_BDLayout.setHorizontalGroup(
            Panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BDLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(Panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Motor_Jlabel)
                    .addComponent(Usuario_Jlabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Contraseña_Jlabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(Panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Usuario_Jtext, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Motores_Jbox, javax.swing.GroupLayout.Alignment.LEADING, 0, 136, Short.MAX_VALUE)
                    .addComponent(Contraseña_Jtext))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_BDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Instancia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_BDLayout.setVerticalGroup(
            Panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BDLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(Panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Motor_Jlabel)
                    .addComponent(Motores_Jbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(Panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuario_Jlabel)
                    .addComponent(Usuario_Jtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Panel_BDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contraseña_Jlabel)
                    .addComponent(Contraseña_Jtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Panel_Instancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_BD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_BD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Panel_BD.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleParent(this);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Motores_JboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Motores_JboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Motores_JboxActionPerformed

    private void Motores_JboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Motores_JboxItemStateChanged
        // TODO add your handling code here:
        deteccion_motor();
        autocompletar();
        if (evt.getStateChange() != -1) {
            deteccion_motor();
        }
    }//GEN-LAST:event_Motores_JboxItemStateChanged

    private void Limpiar_JbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Limpiar_JbotonActionPerformed
        Motores_Jbox.setSelectedIndex(-1);
        Usuario_Jtext.setText("");
        Contraseña_Jtext.setText("");
        Instancia_Jtext.setText("");
        IP_Jtext.setText("");
        Puerto_Jtext.setText("");
        Base_datos_Jtext.setText("");
        Base_datos_Jtext.setEnabled(true);
        Instancia_Jtext.setEnabled(true);
        Base_datos_Jlabel.setEnabled(true);
        Instancia_Jlabel.setEnabled(true);
    }//GEN-LAST:event_Limpiar_JbotonActionPerformed

    private void Instancia_JtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instancia_JtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Instancia_JtextActionPerformed

    private void Puerto_JtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Puerto_JtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Puerto_JtextActionPerformed

    private void Conectar_JbotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Conectar_JbotonActionPerformed
        // TODO add your handling code here:
//        if (campos() == true) {
//            if (CargueLoginUsuario.Conectar(Contraseña_Jtext.getText(), Usuario_Jtext.getText(), Instancia_Jtext.getText(), IP_Jtext.getText(),
//                    Puerto_Jtext.getText(), Base_datos_Jtext.getText(), String.valueOf(Motores_Jbox.getSelectedItem())) == true) {

//                JOptionPane.showMessageDialog(rootPane, "Bienvenido a " + Motores_Jbox.getSelectedItem(), "AUTENTICACION CORRECTA", 1);
                new VentanaPrincipal().setVisible(true);
                dispose();
//            } else {
//                JOptionPane.showMessageDialog(rootPane, "Error en los datos de conexion", "ERROR DE AUTENTICACION", 0);
//            }
      //  }
    }//GEN-LAST:event_Conectar_JbotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            FlatArcIJTheme.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsuarios().setVisible(true);
            }
        });
    }

    public Icon setIcono(String url, JButton boton) {
        ImageIcon icon = new ImageIcon(getClass().getResource(url));
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(20, 20, Image.SCALE_AREA_AVERAGING));
        return icono;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Base_datos_Jlabel;
    public static javax.swing.JTextField Base_datos_Jtext;
    private javax.swing.JButton Conectar_Jboton;
    private javax.swing.JLabel Contraseña_Jlabel;
    private javax.swing.JPasswordField Contraseña_Jtext;
    private javax.swing.JLabel IP_Jlabel;
    public static javax.swing.JTextField IP_Jtext;
    private javax.swing.JLabel Instancia_Jlabel;
    public static javax.swing.JTextField Instancia_Jtext;
    private javax.swing.JButton Limpiar_Jboton;
    private javax.swing.JLabel Motor_Jlabel;
    public static javax.swing.JComboBox<String> Motores_Jbox;
    private javax.swing.JPanel Panel_Instancia;
    private javax.swing.JLabel Puerto_Jlabel;
    public static javax.swing.JTextField Puerto_Jtext;
    private javax.swing.JLabel Usuario_Jlabel;
    public static javax.swing.JTextField Usuario_Jtext;
    // End of variables declaration//GEN-END:variables
}
